name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - uses: CultureHQ/actions-yarn@v1.0.1

    - run: yarn
    - run: yarn check-docs
    - run: yarn check-tests
    # TODO turn this on after fixing all the eslint issues.
    # Some of them are logic related
    # - run: yarn lint
    - run: yarn test
    - run: yarn build
